title: MDmp3 Wiki
description: Documentation for MDmp3.
theme: just-the-docs
color_scheme: mdmp3

logo: "assets/mdmp3wiki.svg"

url: https://cerebralpolicy.github.io/MDmp3-Wiki/

aux_links:
  Template Repository: https://github.com/cerebralpolicy/MDmp3-Wiki
